import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useRouter } from 'next/dist/client/router';
import { useEffect, useState } from 'react';
import { getHeroe } from '../axios/heroAxios';
import { Request } from '../components/main/requestComponent';

export default function Home() {
  const [ids, setIds] = useState([]);

  const route = useRouter();

  useEffect(() => {
    typeof localStorage !== 'undefined' &&
      localStorage.getItem('token') === null &&
      route.replace('/login');
  }, []);

  useEffect(() => {
    getHeroe(ids);
  }, [ids]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Superhero App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Request setIds={setIds} />
    </div>
  );
}
